.PHONY: clean All

All:
	@echo "----------Building project:[ EXERCICE_31 - Debug ]----------"
	@cd "EXERCICE_31" && "$(MAKE)" -f  "EXERCICE_31.mk"
clean:
	@echo "----------Cleaning project:[ EXERCICE_31 - Debug ]----------"
	@cd "EXERCICE_31" && "$(MAKE)" -f  "EXERCICE_31.mk" clean
